#ten compose controluje i sam uruchamia obraz postgresa, nie musze robic tego w konsoli
services:
  postgres-service:
    image: postgres:latest
    container_name: postgres-database
#    environment:
#      - 'POSTGRES_DB=blogdb'
#      - 'POSTGRES_PASSWORD=password'
#      - 'POSTGRES_USER=user'
    env_file:
      - src/main/resources/postgres.env
    ports:
      - '5432:5432' #contaienr:local port
  redis-service:
    image: redis:latest
    container_name: redis-cache
    ports:
      - '6379:6379'



